<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Student;

class StudentSeeder extends Seeder
{
    public function run(): void
    {
        Student::insert([
            [
                'student_code' => 'SV001',
                'full_name' => 'Nguyễn Văn Hoàng',
                'email' => 'nguyenvanhoang@gmail.com',
                'phone' => '0900000001',
                'faculty' => 'Công nghệ thông tin',
                'major' => 'Hệ thống thông tin',
                'class' => '64HTTT1',
                'gpa' => 3.25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_code' => 'SV002',
                'full_name' => 'Nguyễn Thị Thúy Hường',
                'email' => 'nguyenthithuyhuong@gmail.com',
                'phone' => '0900000002',
                'faculty' => 'Công nghệ thông tin',
                'major' => 'Hệ thống thông tin',
                'class' => '64HTTT2',
                'gpa' => 3.45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_code' => 'SV003',
                'full_name' => 'Trần Minh Anh',
                'email' => 'tranminhanh@gmail.com',
                'phone' => '0900000003',
                'faculty' => 'Kinh tế',
                'major' => 'Kinh tế đầu tư',
                'class' => '64KTD1',
                'gpa' => 3.10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_code' => 'SV004',
                'full_name' => 'Lê Hoàng Nam',
                'email' => 'lehoangnam@gmail.com',
                'phone' => '0900000004',
                'faculty' => 'Kỹ thuật xây dựng',
                'major' => 'Xây dựng dân dụng và công nghiệp',
                'class' => '64XDD1',
                'gpa' => 2.85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_code' => 'SV005',
                'full_name' => 'Phạm Ngọc Lan',
                'email' => 'phamngoclan@gmail.com',
                'phone' => '0900000005',
                'faculty' => 'Kinh tế',
                'major' => 'Quản trị kinh doanh',
                'class' => '64QTKD1',
                'gpa' => 3.60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_code' => 'SV006',
                'full_name' => 'Đỗ Quang Huy',
                'email' => 'doquanghuy@gmail.com',
                'phone' => '0900000006',
                'faculty' => 'Công nghệ thông tin',
                'major' => 'Kỹ thuật phần mềm',
                'class' => '64KTPM1',
                'gpa' => 3.35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_code' => 'SV007',
                'full_name' => 'Nguyễn Khánh Linh',
                'email' => 'nguyenkhanhlinh@gmail.com',
                'phone' => '0900000007',
                'faculty' => 'Môi trường',
                'major' => 'Kỹ thuật môi trường',
                'class' => '64MT1',
                'gpa' => 3.05,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_code' => 'SV008',
                'full_name' => 'Vũ Đức Anh',
                'email' => 'vuducanh@gmail.com',
                'phone' => '0900000008',
                'faculty' => 'Kỹ thuật tài nguyên nước',
                'major' => 'Thủy văn và tài nguyên nước',
                'class' => '64TNN1',
                'gpa' => 2.95,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_code' => 'SV009',
                'full_name' => 'Hoàng Thu Trang',
                'email' => 'hoangthutrang@gmail.com',
                'phone' => '0900000009',
                'faculty' => 'Kinh tế',
                'major' => 'Tài chính - Ngân hàng',
                'class' => '64TCNH1',
                'gpa' => 3.50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_code' => 'SV010',
                'full_name' => 'Bùi Thành Đạt',
                'email' => 'buithanhdat@gmail.com',
                'phone' => '0900000010',
                'faculty' => 'Công nghệ thông tin',
                'major' => 'Hệ thống thông tin',
                'class' => '64HTTT3',
                'gpa' => 3.15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_code' => 'SV011',
                'full_name' => 'Phan Thùy Dương',
                'email' => 'phanthuyduong@gmail.com',
                'phone' => '0900000011',
                'faculty' => 'Công nghệ thông tin',
                'major' => 'Khoa học máy tính',
                'class' => '64KHMT1',
                'gpa' => 3.70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_code' => 'SV012',
                'full_name' => 'Đặng Minh Khoa',
                'email' => 'dangminhkhoa@gmail.com',
                'phone' => '0900000012',
                'faculty' => 'Kỹ thuật xây dựng',
                'major' => 'Kinh tế xây dựng',
                'class' => '64KTXD1',
                'gpa' => 2.75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}

